workflow:
  rules:
    # - if: $CI_COMMIT_BRANCH == "develop"
    #   variables:
    #     ENVIRONMENT: development
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        ENVIRONMENT: production

stages:
    - build
    - deploy_npm

build:
    stage: build
    environment:
        name: $ENVIRONMENT
    image: node:latest
    before_script:
        - npm i --omit=dev
    script:
        - npm run build
    artifacts:
        paths:
            - dist
    rules:
        # - if: '$CI_COMMIT_REF_NAME == "develop"'
        #   when: always
        - if: '$CI_COMMIT_REF_NAME == "master"'
          when: always

deploy_npm:
    stage: deploy_npm
    environment:
        name: $ENVIRONMENT
    dependencies:
        - build
    image: node:latest
    before_script:
        - echo "@products:registry=http://${CI_SERVER_HOST}:${CI_SERVER_PORT}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/">.npmrc
        - echo "//${CI_SERVER_HOST}:${CI_SERVER_PORT}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
        # - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
        - npm config list
    script:
        - cd dist
        - npm publish
    rules:
        # - if: '$CI_COMMIT_REF_NAME == "develop"'
        #   when: on_success
        - if: '$CI_COMMIT_REF_NAME == "master"'
          when: on_success